# -*- coding: utf-8 -*-
"""estatisticas+EDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6jiuBR4MOQi8Sz5FMf_AL8R4cUQsrSl
"""

# Simulador de escalonamento com algoritmos de tempo real: Rate Monotonic (RM) e EDF
import random

# Classe para representar um processo
class Processo:
    def __init__(self, pid, chegada, burst, periodo):
        self.pid = pid                    # Identificador do processo
        self.chegada = chegada            # Tempo em que o processo se torna disponível
        self.burst = burst                # Tempo necessário de CPU
        self.periodo = periodo            # Período do processo (define deadline em RM)
        self.deadline = chegada + periodo  # Deadline absoluto inicial
        self.restante = burst             # Tempo restante de execução
        self.inicio = None                # Tempo de início da execução
        self.fim = None                   # Tempo de término da execução
        self.estado = "novo"

# Função para gerar processos periódicos de tempo real
def gerar_processos_reais(qtd):
    processos = []
    for i in range(1, qtd + 1):
        chegada = 0
        burst = random.randint(1, 3)
        periodo = random.randint(4, 10)
        processos.append(Processo(i, chegada, burst, periodo))
    return processos

# Função para simular escalonamento com Rate Monotonic
def simulador_rate_monotonic(processos, tempo_max):
    tempo = 0
    fila = processos.copy()
    tempo_ocupado = 0
    processos_executados = []

    while tempo < tempo_max:
        prontos = [p for p in fila if p.chegada <= tempo and p.restante > 0]
        prontos.sort(key=lambda p: p.periodo)  # Menor período = maior prioridade

        if prontos:
            p = prontos[0]
            if p.inicio is None:
                p.inicio = tempo
            p.restante -= 1
            tempo_ocupado += 1
            if p.restante == 0:
                p.fim = tempo + 1
                processos_executados.append(p)

        tempo += 1

    return processos_executados, tempo, tempo_ocupado

# Função para simular escalonamento com EDF (Earliest Deadline First)
def simulador_edf(processos, tempo_max):
    tempo = 0
    fila = processos.copy()
    tempo_ocupado = 0
    processos_executados = []

    while tempo < tempo_max:
        prontos = [p for p in fila if p.chegada <= tempo and p.restante > 0]
        prontos.sort(key=lambda p: p.deadline)

        if prontos:
            p = prontos[0]
            if p.inicio is None:
                p.inicio = tempo
            p.restante -= 1
            tempo_ocupado += 1
            if p.restante == 0:
                p.fim = tempo + 1
                processos_executados.append(p)

        tempo += 1

    return processos_executados, tempo, tempo_ocupado

# Função para calcular estatísticas de desempenho
def calcular_estatisticas(processos, tempo_total, tempo_ocupado):
    tempos_espera = []
    tempos_retorno = []

    for p in processos:
        espera = (p.inicio - p.chegada) if p.inicio is not None else 0
        retorno = (p.fim - p.chegada) if p.fim is not None else 0
        tempos_espera.append(espera)
        tempos_retorno.append(retorno)

    media_espera = sum(tempos_espera) / len(tempos_espera)
    media_retorno = sum(tempos_retorno) / len(tempos_retorno)
    utilizacao = tempo_ocupado / tempo_total if tempo_total > 0 else 0
    throughput = len(processos) / tempo_total if tempo_total > 0 else 0

    print("\nEstatísticas:")
    print(f"Tempo médio de espera: {media_espera:.2f}")
    print(f"Tempo médio de retorno: {media_retorno:.2f}")
    print(f"Utilização da CPU: {utilizacao:.2%}")
    print(f"Throughput: {throughput:.2f} processos/unidade de tempo")

# Execução do simulador com ambos os algoritmos
if __name__ == "__main__":
    random.seed(42)
    processos = gerar_processos_reais(5)

    print("--- Rate Monotonic ---")
    prontos_rm, tempo_rm, cpu_rm = simulador_rate_monotonic(processos, 20)
    calcular_estatisticas(prontos_rm, tempo_rm, cpu_rm)

    # Regenerar processos (para garantir mesmas características)
    processos = gerar_processos_reais(5)
    print("\n--- EDF (Earliest Deadline First) ---")
    prontos_edf, tempo_edf, cpu_edf = simulador_edf(processos, 20)
    calcular_estatisticas(prontos_edf, tempo_edf, cpu_edf)
